stages:
  - latest
  - next
  - name: release
    if: branch = master
  - name: publish
    if: branch = master

language: node_js

node_js:
  - "10"

jobs:
  include:
    - stage: latest
      on:
        tags: false
      cache: npm
      script: npx semantix latest
    - stage: next
      on:
        tags: false
      cache: npm
      script: npx semantix next
    - stage: release
      on:
        tags: false
      cache: npm
      script: npx semantix release
    - stage: publish
      on:
        tags: false
      cache: npm
      script:
        - export NODE_ENV=production
        - export BABEL_ENV=production
        - npm run build
        - npx semantix update
      deploy:
        skip_cleanup: true
        provider: npm
        email: $NPM_EMAIL
        api_key: $NPM_TOKEN